
# Criação do ingress SIMPLES apenas para o app (blue)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simples-ingress
  # namespace: default
spec:
  ingressClassName: nginx  ### aponta para o ingress class 
  rules:
  - http: 
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-blue # name service da aplicação 
            port:
              number: 80                  



# Acesso app :  http://127.0.0.1.nip.io             



### conceito do ingress class  => Todo ingress é vinclulado ao ingress controle  regra de rota ### 


# saber quantos ingress class tenho no meu ambinente 

# kubectl get ingress

# NAME              CLASS    HOSTS   ADDRESS      PORTS   AGE
# simples-ingress   <none>   *       172.21.0.2   80      4m36s

# kubectl get ingressclass